### ISSUE TITLE
cannot use console (f5)

### ISSUE THREAD

**Issue by Dorrivix** [RandyKnapp/Auga#203] opened 2023-08-24 00:58 UTC
I'm using a test character at the moment to make sure some mods mesh well enough, but I cannot access debug while using this mod.

possibly related to #202

I see the text cursor blip for just a second, but then it doesn't exist. at most I can get a single character in the text field before the cursor goes away, but I have to time it just right to get anything in there.

**Comment by Vapok** [comment] 2023-08-26 16:45
We are having input issues with the new build and this is a known issue.  Apologies!  Will fix as soon as we figure out a path forward.

**Comment by Guildb** [comment] 2023-08-27 23:25
Also I jsut tested with a friend and my friend couldn't write the server password and write the portals names/
The problem is not just on the console.
You maybe already know it but jsut in case :D

**Comment by Vapok** [comment] 2023-09-17 16:08
This is fixed in 1.2.16

**Closed by Vapok** 2023-09-17 16:08 UTC
Labels: bug
